### ISSUE TITLE
ignore file

### ISSUE THREAD

**Issue by MenschLink** [darkmusic/fossil-vscode#15]
it would be nice if not all of my 38000+ files in node_modules would be shown as untracked changes. An ignore file would be nice to have, like .fosignore (analogous to gitignore)

**Comment by JKingweb** [comment]
The equivalent file is `.fossil-settings/ignore-glob`, according to Fossil's documentation.

**Comment by darkmusic** [comment]
Yes, having an ignore-glob file with patterns to ignore works, and also by using the command "fossil ui" (from a command prompt), you can access settings (Admin -> Settings), and set patterns to ignore, such as node-modules, and in this case, this setting is stored in the Fossil database and no ignore-glob file is needed.  Either way is fine though.  Since this is available in Fossil by default already, I will be closing this.
